on:
  workflow_dispatch:
  push:
    branches:
    - main
    
jobs:
  build:
    name: Build the Randomizer
    runs-on: windows-latest
    steps:
      - name: Download bazel
        run: curl -O https://github.com/bazelbuild/bazel/releases/download/7.1.2/bazel-7.1.2-windows-x86_64.exe

      - name: ls
        run: ls

      - name: Build dll
        run: .\bazel-7.1.2-windows-x86_64.exe build :DINPUT8.dll

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: DINPUT8.dll
          path: bazel-bin/DINPUT8.dll
